### ISSUE TITLE
[df] ambassadors, council & notifications [important]

### ISSUE THREAD

**Issue by obernardovieira** [impactMarket/app#201]
### Hugo

- [x] * **Requests are not sorted (should be sorted by updatedAt because the value changes when an ambassador accepts or anything is edited)**

### Bernardo

- [x] * **As ambassador, I see the “report suspicious option” on the sidebar, but shouldn’t. **
- [x] “360” should be 60. Needs to be properly parsed**
- [x] * Community card is breaking -> `Previous PR`
- [x] * Report suspicious activity not opening for beneficiaries -> `Previous PR`

**Comment by hugomarquesdev** [comment]
**Hugo**

[ ] - On decline / accept / claim buttons, call endpoints again and not refresh page
[ ] - As council member I have “my communities” tab. Unless it's ambassador, it's not supposed.
[ ] - **Requests are not sorted (should be sorted by updatedAt because the value changes when an ambassador accepts or anything is edited)**
[ ] - As councilmember, I have a notification that has no title. It only shows “2 days ago”

**Bernardo**

- [ ] As ambassador, I don’t see the “requests” option on the sidebar
- [ ] When ambassador claims community, update only buttons, not the whole page
- [ ] **As ambassador, I see the “report suspicious option” on the sidebar, but shouldn’t. “360” should be 60. Needs to be properly parsed**
- [ ] Community card is breaking
- [ ] If council member has other roles beyond being council member, doesn’t see the proposals menu option
- [ ] Report suspicious activity not opening for beneficiaries
- [ ] If the beneficiary claims the UBI and the community then has no funds, it shows “no funds”, instead of the countdown. Should shown the countdown regardless
